#!/usr/bin/env node
/**
 * Post-build checks for dist/.
 *
 * There is no test suite, so this guards the three things that break quietly
 * and are expensive to notice in production:
 *
 *  1. Documentation anchor ids. These are public URLs linked from outside the
 *     repo, and they are generated by a hand-written port of Sculpin's
 *     algorithm (plugins/satteri-sculpin-headings.mjs). A markdown edit, a
 *     dependency bump or a config change can silently rewrite them. Any id in
 *     the committed snapshot that disappears is a broken deep link.
 *  2. Internal links. Because build.format is 'preserve', a page can be a flat
 *     .html file or a directory index, and it is easy to link to the wrong one.
 *  3. Sitemap entries, which must all resolve.
 *
 * Run with --update-anchors to re-record the snapshot after an *intentional*
 * heading change.
 */
import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const DIST = 'dist';
const SNAPSHOT = 'scripts/anchor-ids.txt';
const update = process.argv.includes('--update-anchors');

const isFile = (p) => { try { return statSync(p).isFile(); } catch { return false; } };
const htmlFiles = (dir) =>
  execFileSync('find', [dir, '-name', '*.html'], { encoding: 'utf8' }).trim().split('\n').filter(Boolean);

let failures = 0;
const fail = (msg) => { failures++; console.error(`FAIL  ${msg}`); };
const ok = (msg) => console.log(`ok    ${msg}`);

if (!existsSync(DIST)) {
  console.error('dist/ not found — run `npm run build` first.');
  process.exit(1);
}

// ---------------------------------------------------------------- 1. anchors
const anchors = new Set();
for (const file of htmlFiles(`${DIST}/documentation`)) {
  for (const m of readFileSync(file, 'utf8').matchAll(/<h[1-6] id="([^"]*)"/g)) anchors.add(m[1]);
}
const current = [...anchors].sort();

if (update) {
  writeFileSync(SNAPSHOT, current.join('\n') + '\n');
  console.log(`recorded ${current.length} anchor ids to ${SNAPSHOT}`);
  process.exit(0);
}

if (!existsSync(SNAPSHOT)) {
  fail(`${SNAPSHOT} is missing — create it with: node scripts/verify-build.mjs --update-anchors`);
} else {
  const expected = readFileSync(SNAPSHOT, 'utf8').split('\n').filter(Boolean);
  const missing = expected.filter((id) => !anchors.has(id));
  const added = current.filter((id) => !expected.includes(id));
  if (missing.length) {
    fail(`${missing.length} documentation anchor id(s) disappeared — these are live URLs:`);
    for (const id of missing.slice(0, 20)) console.error(`        #${id}`);
    console.error('      If the change is intentional: node scripts/verify-build.mjs --update-anchors');
  } else {
    ok(`all ${expected.length} known anchor ids still present${added.length ? ` (${added.length} new)` : ''}`);
  }
}

// ---------------------------------------------------------- 2. internal links
const resolves = (path) =>
  [`${DIST}${path}`, `${DIST}${path}/index.html`, `${DIST}${path}index.html`].some(isFile);

const broken = new Map();
for (const file of htmlFiles(DIST)) {
  const html = readFileSync(file, 'utf8');
  for (const m of html.matchAll(/(?:href|src)="(\/[^"#?]*)/g)) {
    const path = m[1];
    // `//host/…` is a protocol-relative external URL, not a site path.
    if (path.startsWith('//')) continue;
    // /dashboard/ is built separately by install-dashboard.sh, after this runs.
    if (path.startsWith('/_astro/') || path.startsWith('/dashboard') || path.startsWith('/assets/dashboard')) continue;
    if (!resolves(path)) {
      if (!broken.has(path)) broken.set(path, new Set());
      broken.get(path).add(file.slice(DIST.length + 1));
    }
  }
}

// These 404s predate the Astro migration and are reproduced deliberately; see
// the "Known pre-existing quirks" section of CLAUDE.md.
const KNOWN_BROKEN = new Set(['/contact', '/pagenotfound', '/error']);
const unexpected = [...broken.keys()].filter((p) => !KNOWN_BROKEN.has(p));

if (unexpected.length) {
  fail(`${unexpected.length} internal link target(s) do not exist:`);
  for (const p of unexpected.slice(0, 20)) console.error(`        ${p}  (from ${[...broken.get(p)].slice(0, 3).join(', ')})`);
} else {
  ok(`internal links resolve (${KNOWN_BROKEN.size} known pre-existing exceptions ignored)`);
}

// ------------------------------------------------------------------ 3. sitemap
if (!isFile(`${DIST}/sitemap.xml`)) {
  fail('dist/sitemap.xml was not generated');
} else {
  const locs = [...readFileSync(`${DIST}/sitemap.xml`, 'utf8').matchAll(/<loc>([^<]*)<\/loc>/g)].map((m) => m[1]);
  const dead = locs.filter((u) => !resolves(u.replace('https://rokka.io', '')));
  if (dead.length) {
    fail(`${dead.length} sitemap URL(s) do not resolve:`);
    for (const u of dead.slice(0, 20)) console.error(`        ${u}`);
  } else {
    ok(`all ${locs.length} sitemap URLs resolve`);
  }
}

console.log(failures ? `\n${failures} check(s) failed` : '\nall checks passed');
process.exit(failures ? 1 : 0);
